Book.delete_all
Author.delete_all


author1 = Author.new(first_name: "John", prefix: "", last_name: "Grisham", author_img: "http://timemanagement.nl/wp-content/uploads/2014/11/news-grisham.jpg", bio: "John Ray Grisham, Jr. (/ˈɡrɪʃæm/; born February 8, 1955)[2][3] is an American bestselling writer, attorney, politician, and activist best known for his popular legal thrillers. His books have been translated into 42 languages and published worldwide.", quotes:"'Prisons are fascinating places, especially when the inmates are educated, white-collar types.'")

author2 = Author.new(first_name: "Agatha", prefix: "", last_name: "Christie", author_img: "http://a5.files.biography.com/image/upload/c_fill,cs_srgb,dpr_1.0,g_face,h_300,q_80,w_300/MTE5NDg0MDU0OTI0MDY4MzY3.jpg", bio: "Born on September 15, 1890, in Torquay, England, Agatha Christie published her first novel, The Mysterious Affair at Styles, in 1920, and went on to become one of the most famous writers in history, with mysteries like Murder at the Vicarage, Partners in Crime and Sad Cypress. She sold billions of copies of her work, and was also a noted playwright and romance author. She died on January 12, 1976.", quotes: "'One of the luckiest things that can happen to you in life is, I think, to have a happy childhood.'")

author3 = Author.new(first_name: "Danielle", prefix: "", last_name: "Steel", author_img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRaHEwUf1a0L8hSOJNWpUI5cj9ZH6nAO1m_0VLty_226UniZN-u", bio:"Danielle Fernandes Dominique Schuelein-Steel (born August 14, 1947), better known by the name Danielle Steel, is an American novelist, currently the best selling author alive and the fourth bestselling fiction author of all time, with over 800 million copies sold. Based in California for most of her career, Steel has produced several books a year, often juggling up to five projects at once. All her novels have been bestsellers, including those issued in hardback[citation needed]. Her formula is fairly consistent, often involving rich families facing a crisis, threatened by dark elements such as jail, fraud, blackmail and suicide. Steel has also published children's fiction and poetry, as well as raising funds for the treatment of mental disorders. Her books have been translated into 28 languages, with 22 adapted for television, including two that have received Golden Globe nominations.", quotes: "'Sometimes, if you aren't sure about something, you just have to jump off the bridge and grow your wings on the way down.'")

author4 = Author.new(first_name: "Charles", prefix: "", last_name: "Bukowski", author_img: "https://upload.wikimedia.org/wikipedia/commons/7/78/CharlesBukowski-1.jpg", bio: "Henry Charles Bukowski (born Heinrich Karl Bukowski; August 16, 1920 – March 9, 1994) was a German-born American poet, novelist, and short story writer. His writing was influenced by the social, cultural, and economic ambience of his home city of Los Angeles. His work addresses the ordinary lives of poor Americans, the act of writing, alcohol, relationships with women, and the drudgery of work. Bukowski wrote thousands of poems, hundreds of short stories and six novels, eventually publishing over 60 books. The FBI kept a file on him as a result of his column, Notes of a Dirty Old Man, in the LA underground newspaper Open City. In 1986 Time called Bukowski a 'laureate of American lowlife'. Regarding Bukowski's enduring popular appeal, Adam Kirsch of The New Yorker wrote, 'the secret of Bukowski's appeal. . . [is that] he combines the confessional poet's promise of intimacy with the larger-than-life aplomb of a pulp-fiction hero.'", quotes: "'Some people never go crazy. What truly horrible lives they must lead.'")

author5 = Author.new(first_name: "Stephen", prefix: "", last_name: "King", author_img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Stephen_King%2C_Comicon.jpg/220px-Stephen_King%2C_Comicon.jpg", bio: "Stephen Edwin King (born September 21, 1947) is an American author of horror, supernatural fiction, suspense, science fiction, and fantasy. His books have sold more than 350 million copies, many of which have been adapted into feature films, miniseries, television shows, and comic books. King has published 54 novels, including seven under the pen name Richard Bachman, and six non-fiction books. He has written nearly 200 short stories, most of which have been collected in book collections. Many of his stories are set in his home state of Maine. His novella Rita Hayworth and Shawshank Redemption was the basis for the movie The Shawshank Redemption which is widely regarded as one of the greatest films of all time.", quotes: "'Monsters are real, and ghosts are real too. They live inside us, and sometimes, they win.'")


book1 = Book.new(title: "The Whistler", year: 2016, cover_img: "https://s.s-bol.com/imgbase0/imagebase3/regular/FC/1/6/0/2/9200000056172061.jpg",desc: "Lacy Stoltz never expected to be in the firing line. Investigating judicial misconduct by Florida's one thousand judges, her cases so far have been relatively unexciting. That's until she meets Greg Myers, an indicted lawyer with an assumed name, who has an extraordinary tale to tell.",pages: 352,isbn: "9780385541190")
book2 = Book.new(title: "Rogue Lawyer", year: 2016, cover_img: "https://s.s-bol.com/imgbase0/imagebase3/large/FC/6/1/7/7/9200000055247716.jpg",desc: "On the right side of the law. Sort of.
Sebastian Rudd is not your typical street lawyer. He works out of a customized bulletproof van, complete with Wi-Fi, a bar, a small fridge, fine leather chairs, a hidden gun compartment, and a heavily armed driver. He has no firm, no partners, no associates, and only one employee, his driver, who s also his bodyguard, law clerk, confidant, and golf caddy. He lives alone in a small but extremely safe penthouse apartment, and his primary piece of furniture is a vintage pool table. He drinks small-batch bourbon and carries a gun.",pages: 400, isbn: "9781101965863")
book3 = Book.new(title: "Sycamore Row", year: 2014, cover_img: "https://s.s-bol.com/imgbase0/imagebase3/large/FC/4/5/7/9/9200000020099754.jpg",desc: "John Grisham takes you back to where it all began. One of the most popular novels of our time,A Time to Kill established John Grisham as the master of the legal thriller. Now we return to Ford County as Jake Brigance finds himself embroiled in a fiercely controversial trial that exposes a tortured history of racial tension.", pages: 400, isbn:"9781444779547")
book4 = Book.new(title: "And Then There Were None", year: 1971, cover_img: "https://s.s-bol.com/imgbase0/imagebase3/large/FC/4/2/2/6/1001004010926224.jpg", desc: "The Queen of Mystery has come to Harper Collins! Agatha Christie, the acknowledged mistress of suspensecreator of indomitable sleuth Miss Marple, meticulous Belgian detective Hercule Poirot, and so many other unforgettable charactersbrings her entire oeuvre of ingenious whodunits, locked room mysteries, and perplexing puzzles to Harper PaperbacksincludingAnd Then There Were None, the worlds bestselling mystery, in which ten strangers, each with a dark secret, are lured to a mansion on an uninhabited island and killed off one by one.", pages: 300, isbn: "9780062073488")
book5 = Book.new(title: "Murder on the Orient Express", year: 1965, cover_img: "https://s.s-bol.com/imgbase0/imagebase3/large/FC/6/2/2/6/1001004010926226.jpg", desc: "Famous Belgian detective Hercule Poirot must sift through clues--some real and some planted--to find a murderer aboard a crowded train speeding through the snowy European landscape. ", pages: 315, isbn: "9780062073501")
book6 = Book.new(title: "Season of Passion", year: 1979, cover_img: "https://upload.wikimedia.org/wikipedia/en/5/5a/Seasons_of_Passion_book_cover.jpg", desc: "The plot of the book follows Kate meeting Tom Harper, a well known pro-football star, widely recognised across the United States. When first meeting, they enjoyed their relationship, however, after an unsuccessful attempt at suicide, Tom becomes mentally and physically disabled for the rest of his life, leaving Kate pregnant with his unborn son, as well upset about recent circumstances. However, after a chance at a new relationship and fresh start, Kate realises she will have to leave the past behind, to move forward.", pages: 432, isbn: "978-0440177043")
book7 = Book.new(title: "Matters of the Heart", year: 2009, cover_img: "http://www.randomhouse.com/catalog/covers_450/9780440243311.jpg", desc: "Top photographer Hope Dunne has known joy and heartbreak, and finds serenity through the lens of her camera. Content in her Soho loft, she isn’t looking for a man or excitement. But these things find her when she flies to London to photograph one of the world’s most celebrated writers.", pages: 352, isbn: "9780385340274")
book8 = Book.new(title: "Notes of a Dirty Old Man", year: 1969, cover_img: "http://3.bp.blogspot.com/_UN7wPjdKdmc/TLIkKnewNxI/AAAAAAAACdM/f9k_1pg_Bmg/w1200-h630-p-nu/city-lights-notes.jpg", desc: "Notes of a Dirty Old Man is a collection of underground newspaper columns written by Charles Bukowski for the Open City newspaper that were collated and published by Essex House in 1969. His short articles were marked by his trademark crude humor, as well as his attempts to present a 'truthful' or objective viewpoint of various events in his life and his own subjective responses to those events. The series is currently published by City Lights Publishing Company but can also be found in Portions from a Wine-Stained Notebook, which is a collection of all of Bukowski's wide ranging works.", pages: 204, isbn: "978-0872860742")
book9 = Book.new(title: "Women", year: 1978, cover_img: "http://images.gr-assets.com/books/1325028693l/38500.jpg", desc: "Women focuses on the many dissatisfactions Chinaski faced with each new woman he encountered. One of the women featured in the book is a character named Lydia Vance; she is based on Bukowski's one-time girlfriend, the sculptress and sometime poet Linda King. Another central female character in the book is named 'Tanya' who is described as a 'tiny girl-child' and Chinaski's pen-pal. They have a weekend tryst. The real-life counterpart to this character wrote a self-published chapbook about the affair entitled 'Blowing My Hero' under the pseudonym Amber O'Neil. The washed-up folksinger 'Dinky Summers' is based on Bob Lind. In the book, Chinaski's nickname is Hank, which was one of Bukowski's nicknames.", pages: 291, isbn: "978-0753518144")
book10 = Book.new(title: "It", year: 1986, cover_img: "https://s-media-cache-ak0.pinimg.com/originals/1b/24/87/1b2487bac2e314b4d97ae454d81f41ab.jpg", desc: "It is an horror novel by American author Stephen King. The story follows the exploits of seven children as they are terrorized by the eponymous being, which exploits the fears and phobias of its victims in order to disguise itself while hunting its prey. 'It' primarily appears in the form of a clown in order to attract its preferred prey of young children. The novel is told through narratives alternating between two time periods, and is largely told in the third-person omniscient mode. It deals with themes that eventually became King staples: the power of memory, childhood trauma, and the ugliness lurking behind a façade of traditional small-town values. The novel won the British Fantasy Award in 1987, and received nominations for the Locus and World Fantasy Awards that same year. Publishers Weekly listed It as the best-selling book in the United States in 1986." , pages: 1138, isbn: "978-0451169518" )
book11 = Book.new(title: "The Shining", year: 1977, cover_img: "http://www.ciprianmitoceanu.com/wp-content/uploads/2015/05/shining-2.jpg", desc: "The Shining is a horror novel by American author Stephen King. Published in 1977, it is King's third published novel and first hardback bestseller: the success of the book firmly established King as a preeminent author in the horror genre. The setting and characters are influenced by King's personal experiences, including both his visit to The Stanley Hotel in 1974 and his recovery from alcoholism. The novel was followed by a sequel, Doctor Sleep, published in 2013. The Shining centers on the life of Jack Torrance, an aspiring writer and recovering alcoholic who accepts a position as the off-season caretaker of the historic Overlook Hotel in the Colorado Rockies. His family accompanies him on this job, including his young son Danny Torrance, who possesses 'the shining', an array of psychic abilities that allow Danny to see the hotel's horrific past. Soon, after a winter storm leaves them snowbound, the supernatural forces inhabiting the hotel influence Jack's sanity, leaving his wife and son in incredible danger.", pages: 659, isbn: "978-0307743657")
book12 = Book.new(title: "Cujo", year: 1981, cover_img: "https://moly.hu/system/covers/big/covers_214.jpg?1395342916", desc: "Outside a peaceful town in central Maine, a monster is waiting. Cujo is a two-hundred-pound Saint Bernard, the best friend Brett Camber has ever had. One day Cujo chases a rabbit into a bolt-hole - a cave inhabited by sick bats. What happens to Cujo, how he becomes a horrifying vortex inexorably drawing in all the people around him makes for one of the most heart-stopping novels Stephen King has written.", pages: 432, isbn: "978-0307743657")

author1.books << book1
author1.save
author1.books << book2
author1.save
author1.books << book3
author1.save

author2.books << book4
author2.save
author2.books << book5
author2.save

author3.books << book6
author3.save
author3.books << book7
author3.save

author4.books << book8
author4.save
author4.books << book9
author4.save

author5.books << book10
author5.save
author5.books << book11
author5.save
author5.books << book12
author5.save
